### ISSUE TITLE
Ajouter une option pour générer les soldes des comptes

### ISSUE THREAD

**Issue by LucienD** [AFPy/pyash#1]
Ajouter une ligne au debut du fichier pour indiquer les soldes au 1er janvier.

Récupérer le solde de société general et paypal distinctement via les lignes de comptabilité renseigné dans le fichier .ash courant.

Pouvoir les récupérer les soldes distinct, directement via une option de la commande.

**Comment by liZe** [comment]
Corrigé par ea8877a (j’en avais besoin vite pour faire les comptes 2019 :wink:).
